services:
  - type: web
    name: video-uploader-bot
    runtime: python
    repo: https://github.com/HL-HACKER-TEAM/icf-video-hosting-bot
    plan: free
    region: singapore
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: TZ
        value: Asia/Dhaka
